"""shifts, cash movements, sale and purchase returns

Revision ID: 0ab66567e74b
Revises: 8baaf817f71b
Create Date: 2026-09-02 12:28:53.189065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab66567e74b'
down_revision: Union[str, None] = '8baaf817f71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('register_id', sa.Uuid(), nullable=False),
    sa.Column('cashier_id', sa.Uuid(), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opening_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_cash', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closing_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_note', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='shift_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_cashier_id'), 'shifts', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_shifts_organization_id'), 'shifts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shifts_register_id'), 'shifts', ['register_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.Enum('CASH_IN', 'CASH_OUT', name='cash_movement_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_shift_id'), 'cash_movements', ['shift_id'], unique=False)
    op.create_table('purchase_returns',
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('processed_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_returns_organization_id'), 'purchase_returns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_purchase_id'), 'purchase_returns', ['purchase_id'], unique=False)
    op.create_table('sale_returns',
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('processed_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('debt_reduction', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_refund_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_returns_organization_id'), 'sale_returns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sale_returns_sale_id'), 'sale_returns', ['sale_id'], unique=False)
    op.create_table('purchase_return_items',
    sa.Column('purchase_return_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_item_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_item_id'], ['purchase_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_return_items_purchase_return_id'), 'purchase_return_items', ['purchase_return_id'], unique=False)
    op.create_table('sale_return_items',
    sa.Column('sale_return_id', sa.Uuid(), nullable=False),
    sa.Column('sale_item_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_return_items_sale_return_id'), 'sale_return_items', ['sale_return_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_return_items_sale_return_id'), table_name='sale_return_items')
    op.drop_table('sale_return_items')
    op.drop_index(op.f('ix_purchase_return_items_purchase_return_id'), table_name='purchase_return_items')
    op.drop_table('purchase_return_items')
    op.drop_index(op.f('ix_sale_returns_sale_id'), table_name='sale_returns')
    op.drop_index(op.f('ix_sale_returns_organization_id'), table_name='sale_returns')
    op.drop_table('sale_returns')
    op.drop_index(op.f('ix_purchase_returns_purchase_id'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_organization_id'), table_name='purchase_returns')
    op.drop_table('purchase_returns')
    op.drop_index(op.f('ix_cash_movements_shift_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_shifts_register_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_organization_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_cashier_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
