"""billing activation requests and subscription plan

Revision ID: 4f092d911460
Revises: 0ab66567e74b
Create Date: 2026-09-02 13:32:54.494019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f092d911460'
down_revision: Union[str, None] = '0ab66567e74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_requests',
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('plan_requested', sa.Enum('BASIC', 'STANDARD', 'PREMIUM', name='subscription_plan'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='activation_request_status'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_requests_organization_id'), 'activation_requests', ['organization_id'], unique=False)
    op.add_column('organizations', sa.Column('subscription_plan', sa.Enum('BASIC', 'STANDARD', 'PREMIUM', name='subscription_plan'), nullable=True))
    op.add_column('organizations', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'subscription_expires_at')
    op.drop_column('organizations', 'subscription_plan')
    op.drop_index(op.f('ix_activation_requests_organization_id'), table_name='activation_requests')
    op.drop_table('activation_requests')
    # ### end Alembic commands ###
