"""fifo cost layers, discount thresholds, credit limits, transfer and approval permissions

Revision ID: 61f6fcb691bf
Revises: 278433caf26a
Create Date: 2026-09-02 19:47:13.159156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f6fcb691bf'
down_revision: Union[str, None] = '278433caf26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_cost_layers',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('PURCHASE', 'OPENING_BALANCE', 'SALE_RETURN', 'SALE_VOID', 'ADJUSTMENT', name='cost_layer_source'), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_remaining', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_cost_layers_organization_id'), 'inventory_cost_layers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_cost_layers_product_id'), 'inventory_cost_layers', ['product_id'], unique=False)
    op.add_column('organizations', sa.Column('discount_auto_approve_threshold_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'discount_auto_approve_threshold_percent')
    op.drop_index(op.f('ix_inventory_cost_layers_product_id'), table_name='inventory_cost_layers')
    op.drop_index(op.f('ix_inventory_cost_layers_organization_id'), table_name='inventory_cost_layers')
    op.drop_table('inventory_cost_layers')
    # ### end Alembic commands ###
