"""sms config, custom roles infra, billing plans, sms messages, whatsapp storage usage

Revision ID: 64dbdacd0441
Revises: 86ebfc990121
Create Date: 2026-09-02 22:59:54.339353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64dbdacd0441'
down_revision: Union[str, None] = '86ebfc990121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manually added — autogenerate does not detect PostgreSQL enum VALUE
    # renames/additions (MASTER PROMPT §61: Basic/Professional/Business/
    # Enterprise). Any existing row with the old STANDARD/PREMIUM codes is
    # migrated to the new names in the same statement; ENTERPRISE is new.
    op.execute("ALTER TYPE subscription_plan RENAME VALUE 'STANDARD' TO 'PROFESSIONAL'")
    op.execute("ALTER TYPE subscription_plan RENAME VALUE 'PREMIUM' TO 'BUSINESS'")
    op.execute("ALTER TYPE subscription_plan ADD VALUE IF NOT EXISTS 'ENTERPRISE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plan_configs',
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=True),
    sa.Column('max_workers', sa.Integer(), nullable=True),
    sa.Column('whatsapp_quota_monthly', sa.Integer(), nullable=True),
    sa.Column('storage_quota_mb', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Added via raw SQL rather than an inline sa.Enum(...) column: SQLAlchemy
    # tries to CREATE TYPE for any Enum declared inline on op.create_table,
    # even with create_type=False, which collides with the already-existing
    # 'subscription_plan' type altered just above.
    op.execute("ALTER TABLE billing_plan_configs ADD COLUMN code subscription_plan NOT NULL")
    op.execute("ALTER TABLE billing_plan_configs ADD CONSTRAINT uq_billing_plan_configs_code UNIQUE (code)")
    op.create_table('sms_messages',
    sa.Column('message_type', sa.Enum('WORKER_INVITE', 'SALE_RECEIPT', 'DEBT_REMINDER', 'TEST', name='sms_message_type'), nullable=False),
    sa.Column('recipient', sa.String(length=30), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='sms_message_status'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('related_sale_id', sa.Uuid(), nullable=True),
    sa.Column('sent_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_messages_organization_id'), 'sms_messages', ['organization_id'], unique=False)
    op.add_column('expenses', sa.Column('evidence_size_bytes', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('sms_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('organizations', sa.Column('sms_base_url', sa.String(length=300), nullable=True))
    op.add_column('organizations', sa.Column('sms_api_key_encrypted', sa.String(length=1000), nullable=True))
    op.add_column('organizations', sa.Column('sms_sender_id', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('sms_last_tested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('sms_last_test_status', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('sms_last_test_error', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note: PostgreSQL cannot drop an enum value, so ENTERPRISE stays in the
    # type even after downgrade — any row using it would need a manual data
    # migration first. The renames themselves are reversible.
    op.execute("ALTER TYPE subscription_plan RENAME VALUE 'PROFESSIONAL' TO 'STANDARD'")
    op.execute("ALTER TYPE subscription_plan RENAME VALUE 'BUSINESS' TO 'PREMIUM'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'sms_last_test_error')
    op.drop_column('organizations', 'sms_last_test_status')
    op.drop_column('organizations', 'sms_last_tested_at')
    op.drop_column('organizations', 'sms_sender_id')
    op.drop_column('organizations', 'sms_api_key_encrypted')
    op.drop_column('organizations', 'sms_base_url')
    op.drop_column('organizations', 'sms_enabled')
    op.drop_column('expenses', 'evidence_size_bytes')
    op.drop_index(op.f('ix_sms_messages_organization_id'), table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_table('billing_plan_configs')
    # ### end Alembic commands ###
