"""held sales, transfers, account requests, platform owner invitations, usage counters

Revision ID: 86ebfc990121
Revises: 61f6fcb691bf
Create Date: 2026-09-02 20:00:59.222496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ebfc990121'
down_revision: Union[str, None] = '61f6fcb691bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_counters',
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'metric', 'period', name='uq_usage_org_metric_period')
    )
    op.create_index(op.f('ix_usage_counters_organization_id'), 'usage_counters', ['organization_id'], unique=False)
    op.create_table('held_sales',
    sa.Column('register_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('cashier_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_held_sales_organization_id'), 'held_sales', ['organization_id'], unique=False)
    op.create_table('inventory_transfers',
    sa.Column('source_branch_id', sa.Uuid(), nullable=False),
    sa.Column('destination_branch_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'IN_TRANSIT', 'RECEIVED', 'COMPLETED', 'REJECTED', name='transfer_status'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transfers_organization_id'), 'inventory_transfers', ['organization_id'], unique=False)
    op.create_table('platform_owner_invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='platform_owner_invitation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_platform_owner_invitations_email'), 'platform_owner_invitations', ['email'], unique=False)
    op.create_table('tenant_account_requests',
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('applicant_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('business_type', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('expected_usage', sa.String(length=500), nullable=True),
    sa.Column('additional_info', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='account_request_status'), nullable=False),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_account_requests_email'), 'tenant_account_requests', ['email'], unique=False)
    op.create_table('held_sale_items',
    sa.Column('held_sale_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['held_sale_id'], ['held_sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_held_sale_items_held_sale_id'), 'held_sale_items', ['held_sale_id'], unique=False)
    op.create_table('inventory_transfer_items',
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transfer_items_transfer_id'), 'inventory_transfer_items', ['transfer_id'], unique=False)
    op.add_column('expenses', sa.Column('evidence_path', sa.String(length=500), nullable=True))
    op.add_column('expenses', sa.Column('evidence_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'evidence_filename')
    op.drop_column('expenses', 'evidence_path')
    op.drop_index(op.f('ix_inventory_transfer_items_transfer_id'), table_name='inventory_transfer_items')
    op.drop_table('inventory_transfer_items')
    op.drop_index(op.f('ix_held_sale_items_held_sale_id'), table_name='held_sale_items')
    op.drop_table('held_sale_items')
    op.drop_index(op.f('ix_tenant_account_requests_email'), table_name='tenant_account_requests')
    op.drop_table('tenant_account_requests')
    op.drop_index(op.f('ix_platform_owner_invitations_email'), table_name='platform_owner_invitations')
    op.drop_table('platform_owner_invitations')
    op.drop_index(op.f('ix_inventory_transfers_organization_id'), table_name='inventory_transfers')
    op.drop_table('inventory_transfers')
    op.drop_index(op.f('ix_held_sales_organization_id'), table_name='held_sales')
    op.drop_table('held_sales')
    op.drop_index(op.f('ix_usage_counters_organization_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    # ### end Alembic commands ###
