"""org units and enabled payment methods

Revision ID: ca6f50b72696
Revises: 64dbdacd0441
Create Date: 2026-09-03 00:36:08.951511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6f50b72696'
down_revision: Union[str, None] = '64dbdacd0441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_units',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_units_organization_id'), 'organization_units', ['organization_id'], unique=False)
    op.add_column('organizations', sa.Column('enabled_payment_methods', sa.ARRAY(sa.String(length=20)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'enabled_payment_methods')
    op.drop_index(op.f('ix_organization_units_organization_id'), table_name='organization_units')
    op.drop_table('organization_units')
    # ### end Alembic commands ###
